//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Default {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Default() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Default", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Category.
        /// </summary>
        internal static string add_category {
            get {
                return ResourceManager.GetString("add_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Customer.
        /// </summary>
        internal static string add_customer {
            get {
                return ResourceManager.GetString("add_customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Expense.
        /// </summary>
        internal static string add_expense {
            get {
                return ResourceManager.GetString("add_expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Gift Card.
        /// </summary>
        internal static string add_gift_card {
            get {
                return ResourceManager.GetString("add_gift_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Printer.
        /// </summary>
        internal static string add_printer {
            get {
                return ResourceManager.GetString("add_printer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Product.
        /// </summary>
        internal static string add_product {
            get {
                return ResourceManager.GetString("add_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Purchase.
        /// </summary>
        internal static string add_purchase {
            get {
                return ResourceManager.GetString("add_purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Store.
        /// </summary>
        internal static string add_store {
            get {
                return ResourceManager.GetString("add_store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Supplier.
        /// </summary>
        internal static string add_supplier {
            get {
                return ResourceManager.GetString("add_supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        internal static string add_user {
            get {
                return ResourceManager.GetString("add_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply To Order.
        /// </summary>
        internal static string apply_to_order {
            get {
                return ResourceManager.GetString("apply_to_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply To Products.
        /// </summary>
        internal static string apply_to_products {
            get {
                return ResourceManager.GetString("apply_to_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backups.
        /// </summary>
        internal static string backups {
            get {
                return ResourceManager.GetString("backups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string balance {
            get {
                return ResourceManager.GetString("balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill.
        /// </summary>
        internal static string bill {
            get {
                return ResourceManager.GetString("bill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Type.
        /// </summary>
        internal static string card_type {
            get {
                return ResourceManager.GetString("card_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        internal static string cash {
            get {
                return ResourceManager.GetString("cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string categories {
            get {
                return ResourceManager.GetString("categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC.
        /// </summary>
        internal static string cc {
            get {
                return ResourceManager.GetString("cc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC Holder.
        /// </summary>
        internal static string cc_holder {
            get {
                return ResourceManager.GetString("cc_holder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC No.
        /// </summary>
        internal static string cc_no {
            get {
                return ResourceManager.GetString("cc_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cf1.
        /// </summary>
        internal static string cf1 {
            get {
                return ResourceManager.GetString("cf1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cf2.
        /// </summary>
        internal static string cf2 {
            get {
                return ResourceManager.GetString("cf2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque.
        /// </summary>
        internal static string cheque {
            get {
                return ResourceManager.GetString("cheque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque No.
        /// </summary>
        internal static string cheque_no {
            get {
                return ResourceManager.GetString("cheque_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to close.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Register.
        /// </summary>
        internal static string close_register {
            get {
                return ResourceManager.GetString("close_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Quantity.
        /// </summary>
        internal static string current_quantity {
            get {
                return ResourceManager.GetString("current_quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVV2.
        /// </summary>
        internal static string cvv2 {
            get {
                return ResourceManager.GetString("cvv2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        internal static string discount {
            get {
                return ResourceManager.GetString("discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount (5 or 5%).
        /// </summary>
        internal static string discount_title {
            get {
                return ResourceManager.GetString("discount_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string email_address {
            get {
                return ResourceManager.GetString("email_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Info.
        /// </summary>
        internal static string enter_info {
            get {
                return ResourceManager.GetString("enter_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by Reference.
        /// </summary>
        internal static string filter_by_reference {
            get {
                return ResourceManager.GetString("filter_by_reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus Swipe Here.
        /// </summary>
        internal static string focus_swipe_here {
            get {
                return ResourceManager.GetString("focus_swipe_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift Card.
        /// </summary>
        internal static string gift_card {
            get {
                return ResourceManager.GetString("gift_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift Cards.
        /// </summary>
        internal static string gift_cards {
            get {
                return ResourceManager.GetString("gift_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift Card No.
        /// </summary>
        internal static string gift_card_no {
            get {
                return ResourceManager.GetString("gift_card_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold.
        /// </summary>
        internal static string hold {
            get {
                return ResourceManager.GetString("hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Categories.
        /// </summary>
        internal static string import_categories {
            get {
                return ResourceManager.GetString("import_categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Products.
        /// </summary>
        internal static string import_products {
            get {
                return ResourceManager.GetString("import_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Categories.
        /// </summary>
        internal static string list_categories {
            get {
                return ResourceManager.GetString("list_categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Customers.
        /// </summary>
        internal static string list_customers {
            get {
                return ResourceManager.GetString("list_customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Expenses.
        /// </summary>
        internal static string list_expenses {
            get {
                return ResourceManager.GetString("list_expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Gift Cards.
        /// </summary>
        internal static string list_gift_cards {
            get {
                return ResourceManager.GetString("list_gift_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Opened Bills.
        /// </summary>
        internal static string list_opened_bills {
            get {
                return ResourceManager.GetString("list_opened_bills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Products.
        /// </summary>
        internal static string list_products {
            get {
                return ResourceManager.GetString("list_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Purchases.
        /// </summary>
        internal static string list_purchases {
            get {
                return ResourceManager.GetString("list_purchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Sales.
        /// </summary>
        internal static string list_sales {
            get {
                return ResourceManager.GetString("list_sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Suppliers.
        /// </summary>
        internal static string list_suppliers {
            get {
                return ResourceManager.GetString("list_suppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Users.
        /// </summary>
        internal static string list_users {
            get {
                return ResourceManager.GetString("list_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Card.
        /// </summary>
        internal static string master_card {
            get {
                return ResourceManager.GetString("master_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Price.
        /// </summary>
        internal static string net_price {
            get {
                return ResourceManager.GetString("net_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Price.
        /// </summary>
        internal static string new_price {
            get {
                return ResourceManager.GetString("new_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string note {
            get {
                return ResourceManager.GetString("note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string order {
            get {
                return ResourceManager.GetString("order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Tax.
        /// </summary>
        internal static string order_tax {
            get {
                return ResourceManager.GetString("order_tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string other {
            get {
                return ResourceManager.GetString("other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        internal static string payment {
            get {
                return ResourceManager.GetString("payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Note.
        /// </summary>
        internal static string payment_note {
            get {
                return ResourceManager.GetString("payment_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        internal static string people {
            get {
                return ResourceManager.GetString("people", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS.
        /// </summary>
        internal static string POS {
            get {
                return ResourceManager.GetString("POS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printers.
        /// </summary>
        internal static string printers {
            get {
                return ResourceManager.GetString("printers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Barcodes.
        /// </summary>
        internal static string print_barcodes {
            get {
                return ResourceManager.GetString("print_barcodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Bill.
        /// </summary>
        internal static string print_bill {
            get {
                return ResourceManager.GetString("print_bill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Labels.
        /// </summary>
        internal static string print_labels {
            get {
                return ResourceManager.GetString("print_labels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Order.
        /// </summary>
        internal static string print_order {
            get {
                return ResourceManager.GetString("print_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Tax.
        /// </summary>
        internal static string product_tax {
            get {
                return ResourceManager.GetString("product_tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchases.
        /// </summary>
        internal static string purchases {
            get {
                return ResourceManager.GetString("purchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        internal static string qty {
            get {
                return ResourceManager.GetString("qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Note.
        /// </summary>
        internal static string reference_note {
            get {
                return ResourceManager.GetString("reference_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Details.
        /// </summary>
        internal static string register_details {
            get {
                return ResourceManager.GetString("register_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        internal static string sales {
            get {
                return ResourceManager.GetString("sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Gift Card.
        /// </summary>
        internal static string sell_gift_card {
            get {
                return ResourceManager.GetString("sell_gift_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stores.
        /// </summary>
        internal static string Stores {
            get {
                return ResourceManager.GetString("Stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stripe.
        /// </summary>
        internal static string stripe {
            get {
                return ResourceManager.GetString("stripe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string submit {
            get {
                return ResourceManager.GetString("submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        internal static string subtotal {
            get {
                return ResourceManager.GetString("subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspend Sale.
        /// </summary>
        internal static string suspend_sale {
            get {
                return ResourceManager.GetString("suspend_sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax (5 or 5%).
        /// </summary>
        internal static string tax_title {
            get {
                return ResourceManager.GetString("tax_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today&apos;s Sale.
        /// </summary>
        internal static string today_sale {
            get {
                return ResourceManager.GetString("today_sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Items.
        /// </summary>
        internal static string total_items {
            get {
                return ResourceManager.GetString("total_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Payable.
        /// </summary>
        internal static string total_payable {
            get {
                return ResourceManager.GetString("total_payable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Paying.
        /// </summary>
        internal static string total_paying {
            get {
                return ResourceManager.GetString("total_paying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Reference Note.
        /// </summary>
        internal static string type_reference_note {
            get {
                return ResourceManager.GetString("type_reference_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All.
        /// </summary>
        internal static string view_all {
            get {
                return ResourceManager.GetString("view_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa.
        /// </summary>
        internal static string visa {
            get {
                return ResourceManager.GetString("visa", resourceCulture);
            }
        }
    }
}
